// Generated by https://quicktype.io
export interface User {
  data: UserData[];
}

export interface UserById {
  data: UserData;
}

export interface UserData {
  id:           string;
  code:         string;
  email:        string;
  nombre:       string;
  apellido:     string;
  isActive:     boolean;
  permissions:  string;
  role:         string;
}

export interface Token {
  sub:      number;
  code:     string;
  email:    string;
  nombre:   string;
  apellido: string;
  role:     string;
  iat:      number;
  exp:      number;
  aud:      string;
}
