// Generated by https://quicktype.io
export interface Electricidad {
  data: ElectricidadResponse[];
}

export interface TipoElectricidadResponse{
  data: TipoElectricidad[];
}

export interface ElectricidadResponse {
  id:                   string;
  tipo_electricidad_id: string;
  cantidad:             number;
  fecha_ingreso:        string;
  factura:              string;
  area:                 string;
  evidencia_url:        string;
  createdAt:            string;
  updatedAt:            null;
  persona_upsert:       string;
  tipo_electricidad:    TipoElectricidad;
}

export interface TipoElectricidad {
  id:          string;
  nombre:      string;
  unidad:      string;
  factor:      number;
  valor_neto:  number;
  co2:         number;
  ch4:         number;
  n2o:         number;
  flag_activo: boolean;
}

export interface ElectricidadRegister{
  id:                   number,
  tipo_electricidad_id: number,
  cantidad:             number,
  fecha_ingreso:        string,
  factura:              string,
  area:                 string,
  evidencia_url:        string
}
