// Generated by https://quicktype.io

export interface Consumosein {
  data: Consumoseinresponsive[];
}

export interface TipoConsumosein {
  data: TipoConsumoSein[];
}


export interface Consumoseinresponsive {
  id:                   string;
  tipo_consumo_sein_id: string;
  suministro:           string;
  cantidad:             number;
  fecha_ingreso:        string;
  area:                 string;
  evidencia_url:        string;
  createdAt:            string;
  updatedAt:            null;
  persona_upsert:       string;
  tipo_consumo_sein:    TipoConsumoSein;
}

export interface TipoConsumoSein {
  id:          string;
  unidad:      string;
  factor:      number;
  co2:         number;
  ch4:         number;
  n2o:         number;
  flag_activo: boolean;
}

export interface ConsumoseinRegister{
  id:                   number;
  tipo_consumo_sein_id: string;
  suministro:           string;
  cantidad:             number;
  fecha_ingreso:        string;
  area:                 string;
  evidencia_url:        string;
}
