// Generated by https://quicktype.io

export interface Refrigerantesresponsive {
  data: Refrigerante[];
}

export interface Refrigerante {
  id:                     number;
  tipo_refrigerante_id:   number;
  equipo_refrigerante_id: number;
  cantidad:               number;
  capacidad_carga:        number;
  fuga_instalacion:       number;
  porcentaje_fuga:        number;
  fecha_ingreso:          string;
  fuga_uso:               number;
  tiempo_uso:             number;
  fraccion_disposicion:   number;
  fraccion_recuperacion:  number;
  area:                   string;
  evidencia_url:          string;
  createdAt:              string;
  updatedAt:              null;
  persona_upsert:         string;
  tipo_refrigerante:      Tipo;
  equipo_refrigerante:    Equipo;
}

export interface RefrigeranteEquipo {
  data: Equipo[];
}

export interface Equipo {
  id:          string;
  nombre:      string;
  flag_activo: boolean;
}

export interface RefrigeranteTipo {
  data: Tipo[];
}

export interface Tipo {
  id:          string;
  nombre:      string;
  flag_activo: boolean;
}

export interface RefrigeranteRegistar {
  id:                     number;
  tipo_refrigerante_id:   number;
  equipo_refrigerante_id: number;
  cantidad:               number;
  capacidad_carga:        number;
  fuga_instalacion:       number;
  porcentaje_fuga:        number;
  fecha_ingreso:          string;
  area:                   string;
  fuga_uso:               number;
  tiempo_uso:             number;
  fraccion_disposicion:   number;
  fraccion_recuperacion:  number;
  evidencia_url:          string;
}
